name: CI-CD
on:
  push:
    branches:
      - main

jobs:
  filter-paths:
    name: Determine changed paths
    id: filter
    steps:
      - uses: actions/checkout@v3
      - determine-paths:
        uses: dorny/paths-filter@v2
        with:
          filters: |
            crkbd-qmk:
              - './crkbd/qmk'
            crkbd-via:
              - './crkbd/via'

  crkbd-qmk:
    name: Release crkbd qmk
    if: steps.filter.outputs.crkbd-qmk == 'true'
    steps:
      - uses: ./.github/workflows/crkbd-qmk.yml

  crkbd-via:
    name: Release crkbd via
    if: steps.filter.outputs.crkbd-via == 'true'
    steps:
      - uses: ./.github/workflows/crkbd-via.yml
