name: CI-CD
on:
  push:
    branches:
      - main

jobs:
  filter:
    name: Determine changed paths
    runs-on: ubuntu-latest
    outputs:
      crkbd-qmk: ${{ steps.filter.outputs.crkbd-qmk }}
      crkbd-via: ${{ steps.filter.outputs.crkbd-via }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            crkbd-qmk:
              - './crkbd/qmk/**'
            crkbd-via:
              - './crkbd/via/**'

  crkbd-qmk:
    name: Release crkbd qmk
    needs: filter
    if: needs.filter.outputs.crkbd-qmk == 'true'
    uses: ./.github/workflows/crkbd-qmk.yml

  crkbd-via:
    name: Release crkbd via
    needs: filter
    if: needs.filter.outputs.crkbd-via == 'true'
    uses: ./.github/workflows/crkbd-via.yml
