name: Release crkbd via
on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write

    steps:
      - uses: actions/checkout@v3
      - uses: codfish/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [ 'main' ]
          tag_format: '@crkbd/via@${version}'
          plugins: |
            [
              ['@semantic-release/commit-analyzer', {
                "releaseRules": [
                  { "type": "tweak", "release": "patch" }
                ]
              }],
              ['@semantic-release/release-notes-generator', {
                "presetConfig": {
                  "types": [
                    {"type": "feat", "section": "Features"},
                    {"type": "fix", "section": "Bug Fixes"},
                    {"type": "tweak", "section": "Tweaks"}
                    {"type": "chore", "hidden": true},
                    {"type": "docs", "hidden": true},
                    {"type": "style", "hidden": true},
                    {"type": "refactor", "hidden": true},
                    {"type": "perf", "hidden": true},
                    {"type": "test", "hidden": true}
                  ]
                }
              }],
              ['@semantic-release/github', {
                "assets": [
                  { "path": "crkbd/via/layout.json", "name": "crkbd_layout.json", "label": "crkbd via layout" }
                ]
              }]
            ]
