name: Release crkbd via
on:
  workflow_call:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: codfish/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          dry_run: true
          branches: |
            [ 'main' ]
          tag_format: '@crkbd/via@${version}'
          plugins: |
            [
              '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              ['@semantic-release/github', {
                "assets": [
                  { "path": "crkbd/via/layout.json", "label": "crkbd via layout" }
                ]
              }]
            ]
