name: Release crkbd qmk
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false

    steps:
      - name: Disable git safe directory checks
        run: git config --global --add save.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v3
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk_firmware
          ref: ba10b87063e6911445103ca1f925edadc4b179c3

      - name: Checkout userspace
        uses: actions/checkout@v3
        with:
          path: kbd

      - name: Move and rename crkbd qmk setup
        run: cp -rT kbd/crkbd/qmk qmk_firmware/keyboards/crkbd/keymaps/${{ github.actor }}

      - name: Configure QMK CLI
        run: |
          qmk config user.qmk_home="$PWD/qmk_firmware"
          qmk config user.keyboard=crkbd/rev1
          qmk config user.keymap=${{ github.actor }}

      - name: Build firmware
        run: qmk compile

      - name: Archive firmware
        uses: actions/upload-artifact@v3
        continue-on-error: true
        with:
          name: crkbd_rev1_${{ github.actor }}
          path: |
            qmk_firmware/*.hex
            qmk_firmware/*.bin
            qmk_firmware/*.uf2

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      statuses: write

    steps:
      - uses: actions/checkout@v3

      - name: Download firmware
        uses: actions/download-artifact@v3
        with:
          name: crkbd_rev1_${{ github.actor }}

      - uses: codfish/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: |
            [ 'main' ]
          tag_format: '@crkbd/qmk@${version}'
          additional-packages: |
            [ '@semantic-release/commit-analyzer',
              '@semantic-release/release-notes-generator',
              '@semantic-release/github' ]
          plugins: |
            [
              ['@semantic-release/commit-analyzer', {
                "releaseRules": [
                  { "type": "tweak", "release": "patch" }
                ]
              }],
              ['@semantic-release/release-notes-generator', {
                "presetConfig": {
                  "types": [
                    {"type": "feat", "section": "Features"},
                    {"type": "fix", "section": "Bug Fixes"},
                    {"type": "tweak", "section": "Tweaks"}
                    {"type": "chore", "hidden": true},
                    {"type": "docs", "hidden": true},
                    {"type": "style", "hidden": true},
                    {"type": "refactor", "hidden": true},
                    {"type": "perf", "hidden": true},
                    {"type": "test", "hidden": true}
                  ]
                }
              }],
              ['@semantic-release/github', {
                "assets": [
                  { "path": "crkbd_rev1_*.hex", "name": "crkbd_rev1_firmware.hex", "label": "crkbd qmk firmware" }
                ]
              }]
            ]
